apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Release.Name }}-nginx
  {{- if .Values.depLabel}}
  labels:
    app: hello-world
    {{- template  "labels"  . }} ## .(dot) passes the context from k8s manifest file to helper named template
  {{- else if eq  .Values.depLabel  "frontnd" }}
  labels:
      app: frontend-deployment
  {{- end }}
spec:
  replicas: {{  .Values.app.deploymentData.replicaCount }}
  selector:
    matchLabels:
      {{- include "labels" . | indent  2 }} # type helper named template , it will be used when we want apply some functions also like indent here
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "labels"  . | indent  4 }} # type helper named template , it will be used when we want apply some functions also like indent here
    spec:
      containers:
      - image: {{ default "nginx" .Values.image.repo  }} # setting default image using default func
        name: {{  .Values.container.name  | upper | quote }} # using multiple functions
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        resources: {}
status: {}
