{{- if .Values.app.createService  }}

{{- with .Values.app  }}
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  {{- with .serviceData }}
  type: NodePort
  ports:
  {{- with  .ports  }}
    - port: {{  .port }}
      targetPort: {{  .targetPort }}
      protocol: {{  .protocol }}
      name: {{  .name }}
  {{- end}}
  selector:
      app: hello-world
  {{- end }}
{{- end }}

{{- end }}